"""Builds ExtractThis.luau from Source.lua + bootstrap.luau."""

from pathlib import Path

parent = Path(__file__).resolve().parent

source = (parent / 'Source.lua').read_text(encoding='utf-8')
tail = (parent / 'bootstrap.luau').read_text(encoding='utf-8')

built = (
    '-- ExtractThis.luau — GENERATED by build.py (Source.lua + bootstrap.luau), do not edit.\n'
    '-- Paste into a ModuleScript named "ExtractThis" under Workspace, publish, join the place\n'
    '-- with the Roblox player, then run src/helpers/dump.py to regenerate init.bin.\n'
    '\n'
    'local fiu = (function()\n'
    + source
    + '\nend)()\n'
    + '\n'
    + tail
)

(parent / 'ExtractThis.luau').write_text(built, encoding='utf-8')
print('built ExtractThis.luau')
